### ISSUE TITLE
[bit.no]: issues on https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#16]
Fehlermeldung:
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://bit.no.com:43110/1NP1a1aUghi3R6CEtA2WDCzDWE4n9xWmFf/data/users/13rSqUxKrRUxSGpbQ3qkE8zpiKYUuZaUCF/data.json. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

**Comment by dnelband** [comment]
done

**Comment by haschimoto** [comment]
doesnt load any video content with chrome (ff works)

**Comment by dnelband** [comment]
Done

**Comment by haschimoto** [comment]
still getting this:
![snap 2016-08-25 at 10 08 40](https://cloud.githubusercontent.com/assets/20817185/17961455/17b45ef4-6aac-11e6-9264-125dddb74524.png)

**Comment by haschimoto** [comment]
- clicking on asd.webm shows player with "null" length
- sometimes a big circle appears and loads forever

**Comment by dnelband** [comment]
1 - the error - it has something to do specifically with bit.no.com & the sidebar (it only happens when you drag the sidebar). this doesnt happen localy. ive spent more then an hour on this, deleted all the files but it still appears this error. this could be fixed after the server reloads (it happens every couple of days) or we can move the site to a new address. for example ive cloned the site to this address https://bit.no.com:43110/1BpsXQc6aUTt3bFQUvT9NvGFLcf1ZNEuX3/ and here it doesnt show this error. theres no explanation for this error anywhere - "Internal error: KeyError: u'data/users/1JfCU6LebMF14gnUxAxzGS2q5y2s5fmwoA/content.json'"

2 - this video is deleted

3 - some videos are either deleted or have only the .json file. what should be displayed in this case? video not found or something like that?

**Comment by haschimoto** [comment]
2 - but if you click on the channel, some stuff that shows "NULL" loads and runs just fine in the channel....

3 - yes instead of endlessly loading....

**Comment by dnelband** [comment]
1 - the error message no longer appears if you drag the zero ( im not sure why )
2 - there are some videos that only have a .json file (and are missing the actual media file) so they play only on firefox. newer videos will not have this problem. but anyway ill write a workaround for these specific videos.
3 - ok

**Comment by dnelband** [comment]
done. those videos that only have .json play on chrome. in case file wasnt found a message with "file not found" is displayed.

**Comment by haschimoto** [comment]
well, lets really get this done 100%:

[ ] Question:
We do not have TWO files for each media type, one "real" + one "json", or do we? That would be total waste of effort to spread optional files.

[ ] Todo chrome:
- on chrome, i click ahey.mp4 and it doesnt show it loads anyhing and  NULL, but after 15-20 seconds the video plays: the video player should show its loading something in the back, like keep that wheel spinning and show "loading" underneath until something is initialized.

[ ] Todo ff:
- on firefox, the file ahey also takes 10-20 seoonds, but any other file still plays.
  Selecting any media from the sidebar should also STOP anything, and immediatly initilaize the videoplayer with the spinning wheel indicating it is loading something.

**Comment by haschimoto** [comment]
adding:
in ff its even worse: when a file is PAUSED, if you click on any other file at sidebar, nothing happens.
You need to unpause the current file before it takes another few seconds that the player starts loading the previously clicked file.

**Comment by haschimoto** [comment]
summary ff and chrome:
whenever a file is clicked, the videoplayer needs to be stop anything thats currently playing and show a spinning wheel + "loading" underneath so the user knows it is trying to get the content until that is done and the player starts playing the file. Pausing should not prevent this on FF. 
We should always store and seed only 1 instance of a file.

**Comment by haschimoto** [comment]
if a file is buffered enough and ready to play, stop the spinwheel and start playing immediatly.

**Comment by dnelband** [comment]
question - until now yes, we had two versions. we did it then because of the firefox compatibility, due to the fact that firefox doesnt allow the media files to play (cross origin, iframe). so we need to cancel that solution, and ill find some other solution to play the files on firefox. this means that all the bugs / errors that were assosiated with old files (which have only .json version) are irrelevant.

chrome - works, check new files or the mp3. clicking on an older file with only json will not work then from this point on.

firefox - we are droping the .json solution, another solution is needed. im working on it

**Comment by dnelband** [comment]
firefox - fixed, now loading regular files! but still has a bit different process then chrome (file is first fetched as blob). there are still problems with the buffering & navigating through videos is still a bit buggy, im working on it

**Comment by dnelband** [comment]
ok you can test now on firefox

**Comment by haschimoto** [comment]
its not clean here:
you click on "California Dreaming" it says "file not found"
then click on dn2016.0804.mp4 and it shows NULL and no spin circle
if you click on samoe.mp4, iot loads the video, then you click on dn2016.0804 and it shows spinning circle until loaded...

so depending on the previous video found or not, the next video will display different things, even if clicked on the same video file!!!

**Comment by haschimoto** [comment]
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/
tested with chrome
