### ISSUE TITLE
[user]: uploaded file seems not counted under "Optional Files" - Total size

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#21]
where are the 8.9 MB?
![snap 2016-08-25 at 23 01 19](https://cloud.githubusercontent.com/assets/20817185/17986266/1755489c-6b1a-11e6-9fd2-b1da64c26aa9.png)

**Comment by haschimoto** [comment]
maybe thats why it doesnt load: 
https://bit.no.com:43110/1JuT6WhcqbTYtCqmq4qpqpN141gkv1YPQV/video.html?w=1

**Comment by dnelband** [comment]
please test on a new channel, this has also some unrelated js errors that i fixed

**Comment by haschimoto** [comment]
i cloned again, uploaded and it still not fixed....
please do a ticket completely 100% foolproof and test it 1000 times before reporting it is fixed, it is not....

**Comment by haschimoto** [comment]
http://127.0.0.1:43110/1FUUHRYeDE7UeUNXc8GSYuX3sqDen39ZLi

**Comment by haschimoto** [comment]
![snap 2016-08-26 at 21 50 11](https://cloud.githubusercontent.com/assets/20817185/18018429/21167ec4-6bd7-11e6-8a15-4eafc089357e.png)

**Comment by dnelband** [comment]
yes but what is the bug exactly here? how should it be shown? 

i dont understand this ticket, its a question - "uploaded file seems not counted under optional download size nor normal size?" - what should i do here? should it be counted? all the media & data files in /uploads/.\* & /data/.\* are optional, i didnt change that. 

what do you mean exactly with this ticket? i dont understand from the title what im supposed to do

**Comment by haschimoto** [comment]
Optional files are shown with size, but it says 0.... that is not correct!
Optional files ARE counted and if it says 0 MB, then something is wrong for certain.

**Comment by haschimoto** [comment]
e.g. all files from the early NES games channel are optional and counted in Total:
![snap 2016-08-27 at 11 53 26](https://cloud.githubusercontent.com/assets/20817185/18026603/178774aa-6c4d-11e6-9ed7-b533401de74c.png)

**Comment by haschimoto** [comment]
okay, this seems also related to the filename issue....
as seen here, each optional file NEEDS to be counted in total, as well as in Downloaded since you uploaded its already in your cache "donwloaded"...
![snap 2016-08-27 at 12 02 48](https://cloud.githubusercontent.com/assets/20817185/18026648/66560988-6c4e-11e6-9d0e-215db74ea712.png)

**Comment by haschimoto** [comment]
so something is definately wrong when you upload and its not listed as optional file "Total" size.
I'll close this here since there are other reasons why it had 0 size and didnt show up.
