### ISSUE TITLE
[central]: add voting up/down

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#4]

**Comment by dnelband** [comment]
done

**Comment by haschimoto** [comment]
i get this error and look:
![snap 2016-08-11 at 20 07 15](https://cloud.githubusercontent.com/assets/20817185/17599433/5885e374-5fff-11e6-94c9-d75ff375b1e0.png)

**Comment by haschimoto** [comment]
okay, after updating again vote seems to work, but still get an error message:
![snap 2016-08-11 at 20 11 52](https://cloud.githubusercontent.com/assets/20817185/17599545/ede6d298-5fff-11e6-8b85-dccae94d88e0.png)

**Comment by dnelband** [comment]
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/?c=1PP34sdjvazPUvCGs7cUp8wLUwYRsdDT24v=1

works without error message. should this be updated automatically every x minutes or so?
